/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hn.uth.poo.p3;

import hn.uth.poo.p3.recursos.clases.Cliente;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class frmCliente extends javax.swing.JFrame {

    /**
     * Creates new form Cliente
     */    
    DefaultTableModel modelo;
    int fila;
    public frmCliente() {
        initComponents();
        modelo = (DefaultTableModel) tblDatos.getModel();
        setSize(750, 625);
        setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblIdentidad = new javax.swing.JLabel();
        txtRtn = new javax.swing.JTextField();
        txtLicencia = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        lblRtn = new javax.swing.JLabel();
        lblLicencia = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        txtDireccion1 = new javax.swing.JTextField();
        Direccion = new javax.swing.JLabel();
        btnRegistrar1 = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        lblTitulo.setText("Sección Cliente");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(260, 10, 240, 20);

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre);
        txtNombre.setBounds(10, 50, 120, 30);

        lblNombre.setBackground(new java.awt.Color(0, 204, 204));
        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblNombre.setText("Nombre:");
        getContentPane().add(lblNombre);
        lblNombre.setBounds(40, 90, 46, 15);

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        getContentPane().add(txtId);
        txtId.setBounds(150, 50, 130, 30);

        lblIdentidad.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblIdentidad.setText("Identidad:");
        getContentPane().add(lblIdentidad);
        lblIdentidad.setBounds(180, 90, 53, 15);

        txtRtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRtnActionPerformed(evt);
            }
        });
        getContentPane().add(txtRtn);
        txtRtn.setBounds(290, 50, 130, 30);
        getContentPane().add(txtLicencia);
        txtLicencia.setBounds(430, 50, 130, 30);
        getContentPane().add(txtTelefono);
        txtTelefono.setBounds(570, 50, 120, 30);

        lblRtn.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lblRtn.setText("RTN:");
        getContentPane().add(lblRtn);
        lblRtn.setBounds(330, 90, 40, 18);

        lblLicencia.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lblLicencia.setText("Licencia");
        getContentPane().add(lblLicencia);
        lblLicencia.setBounds(460, 80, 70, 30);

        lblTelefono.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lblTelefono.setText("Telefono:");
        lblTelefono.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(lblTelefono);
        lblTelefono.setBounds(590, 70, 80, 40);
        getContentPane().add(txtCorreo);
        txtCorreo.setBounds(160, 120, 140, 30);
        getContentPane().add(txtDireccion);
        txtDireccion.setBounds(410, 120, 160, 30);

        lblCorreo.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lblCorreo.setText("Correo");
        getContentPane().add(lblCorreo);
        lblCorreo.setBounds(210, 140, 60, 40);
        getContentPane().add(txtDireccion1);
        txtDireccion1.setBounds(410, 120, 160, 30);

        Direccion.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Direccion.setText("Barrio/Colonia");
        getContentPane().add(Direccion);
        Direccion.setBounds(440, 140, 120, 40);

        btnRegistrar1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\proyecto final oficial\\src\\main\\java\\hn\\uth\\poo\\p3\\recursos\\imagenes1\\icons8-check-file-16.png")); // NOI18N
        btnRegistrar1.setText("Registrar");
        btnRegistrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar1);
        btnRegistrar1.setBounds(140, 180, 100, 40);

        btnActualizar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\proyecto final oficial\\src\\main\\java\\hn\\uth\\poo\\p3\\recursos\\imagenes1\\icons8-refresh-16.png")); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar);
        btnActualizar.setBounds(290, 180, 110, 40);

        btnEliminar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\proyecto final oficial\\src\\main\\java\\hn\\uth\\poo\\p3\\recursos\\imagenes1\\icons8-delete-document-16.png")); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(430, 180, 100, 40);

        btnLimpiar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\proyecto final oficial\\src\\main\\java\\hn\\uth\\poo\\p3\\recursos\\imagenes1\\limpiar.png")); // NOI18N
        btnLimpiar.setText("Limpiar campos");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar);
        btnLimpiar.setBounds(250, 230, 160, 40);

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Identidad", "RTN", "Licencia", "Telefono", "Correo", "Dirección"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDatos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 270, 600, 400);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\proyecto final oficial\\src\\main\\java\\hn\\uth\\poo\\p3\\recursos\\imagenes1\\3.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 710, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtRtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRtnActionPerformed

    private void btnRegistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrar1ActionPerformed
        // TODO add your handling code here:
        try {
            Cliente cliente = new Cliente();

            cliente.setNombre(txtNombre.getText());
            cliente.setId(Integer.parseInt(txtId.getText()));
            cliente.setRtn(Integer.parseInt(txtRtn.getText()));
            cliente.setLicencia(txtLicencia.getText());
            cliente.setTelefono(Integer.parseInt(txtTelefono.getText()));
            cliente.setCorreo(txtCorreo.getText());
            cliente.setDireccion(txtDireccion.getText());
            Object registroLeido[] = {cliente.getNombre(), cliente.getId(), cliente.getRtn(), cliente.getLicencia(), cliente.getTelefono(), cliente.getCorreo(), cliente.getDireccion()};
            modelo.addRow(registroLeido);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnRegistrar1ActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        try {
            String info[]=new String[7];
            info[0]=txtNombre.getText();
            info[1]=txtId.getText();
            info[2]=txtRtn.getText();
            info[3]=txtLicencia.getText();
            info[4]=txtTelefono.getText();
            info[5]=txtCorreo.getText();
            info[6]=txtDireccion.getText();
            for (int i = 0; i < tblDatos.getColumnCount(); i++) {
                modelo.setValueAt(info[i], fila, i);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int elijoBotonParaEliminar = JOptionPane.showConfirmDialog(null, "¿Desea eliminar?","Mensaje",JOptionPane.OK_CANCEL_OPTION);
        if (elijoBotonParaEliminar==0) {
            try {
                Cliente clientes = new Cliente();
                clientes.setNombre(txtNombre.getText());
                clientes.setId(Integer.parseInt(txtId.getText()));

                clientes.setRtn(Integer.parseInt(txtRtn.getText()));
                clientes.setTelefono(Integer.parseInt(txtTelefono.getText()));
                clientes.setCorreo(txtCorreo.getText());
                clientes.setDireccion(txtDireccion.getText());
                clientes.setLicencia(txtLicencia.getText());
                int FilaSeleccionada=tblDatos.getSelectedRow();
                modelo.removeRow(FilaSeleccionada);
                JOptionPane.showMessageDialog(null, "ELIMINADO", "EXITO", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            }

        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tblDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDatosMouseClicked
        // TODO add your handling code here:
        int FilaSeleccionada = tblDatos.getSelectedRow();

        txtNombre.setText(modelo.getValueAt(FilaSeleccionada, 0).toString());
        txtId.setText(modelo.getValueAt(FilaSeleccionada, 1).toString());
        txtRtn.setText(modelo.getValueAt(FilaSeleccionada, 2).toString());
        txtLicencia.setText(modelo.getValueAt(FilaSeleccionada, 3).toString());
        txtTelefono.setText(modelo.getValueAt(FilaSeleccionada, 4).toString());
        txtCorreo.setText(modelo.getValueAt(FilaSeleccionada, 5).toString());
        txtDireccion.setText(modelo.getValueAt(FilaSeleccionada, 6).toString());
        fila=FilaSeleccionada;
    }//GEN-LAST:event_tblDatosMouseClicked

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        LimpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed
    public void LimpiarCampos() {
        txtNombre.setText("");
        txtId.setText("");
        txtCorreo.setText("");
        txtDireccion.setText("");
        txtLicencia.setText("");
        txtRtn.setText("");
        txtTelefono.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Direccion;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblIdentidad;
    private javax.swing.JLabel lblLicencia;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRtn;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDireccion1;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLicencia;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRtn;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
