/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hn.uth.poo.p3;

import hn.uth.poo.p3.recursos.clases.Factura;
import hn.uth.poo.p3.recursos.clases.Servicios;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class frmFactura extends javax.swing.JFrame {

    /**
     * Creates new form frmFactura
     */
    public frmFactura() {
        initComponents();
        setSize(625, 822);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frmFactura = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCambio = new javax.swing.JTextField();
        txtRtn = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtPlaca = new javax.swing.JTextField();
        txtPrecioRepuestos = new javax.swing.JTextField();
        txtEfectivo = new javax.swing.JTextField();
        txtSubTotal = new javax.swing.JTextField();
        txtISV = new javax.swing.JTextField();
        txtDescuento = new javax.swing.JTextField();
        txtTotalPagar = new javax.swing.JTextField();
        cboLista = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        cbxRtn = new javax.swing.JComboBox<>();
        txtCant = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        frmFactura.setAlignment(java.awt.Label.CENTER);
        frmFactura.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        frmFactura.setText("Factura\n");
        getContentPane().add(frmFactura);
        frmFactura.setBounds(250, 20, 158, 40);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setText("Nombre\n\n");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 90, 59, 21);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("RTN");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 130, 33, 21);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Telefono\n");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 180, 65, 21);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Placa\n");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 220, 42, 21);

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cambio");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 610, 57, 21);

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Precio de  Repuestos ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(100, 300, 131, 17);

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cantidad de Repuestos");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(100, 260, 138, 17);

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Sub Total");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(110, 400, 72, 21);

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ISV");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(110, 450, 26, 21);

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Descuento");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(100, 490, 69, 18);

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Total a Pagar");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(90, 530, 88, 18);

        txtCambio.setEditable(false);
        txtCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCambioActionPerformed(evt);
            }
        });
        getContentPane().add(txtCambio);
        txtCambio.setBounds(330, 610, 160, 30);

        txtRtn.setEnabled(false);
        txtRtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRtnActionPerformed(evt);
            }
        });
        getContentPane().add(txtRtn);
        txtRtn.setBounds(330, 130, 160, 30);
        getContentPane().add(txtTelefono);
        txtTelefono.setBounds(330, 170, 160, 30);
        getContentPane().add(txtPlaca);
        txtPlaca.setBounds(330, 210, 160, 30);

        txtPrecioRepuestos.setEditable(false);
        txtPrecioRepuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioRepuestosActionPerformed(evt);
            }
        });
        getContentPane().add(txtPrecioRepuestos);
        txtPrecioRepuestos.setBounds(330, 290, 160, 30);

        txtEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEfectivoActionPerformed(evt);
            }
        });
        getContentPane().add(txtEfectivo);
        txtEfectivo.setBounds(330, 570, 160, 30);

        txtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubTotalActionPerformed(evt);
            }
        });
        getContentPane().add(txtSubTotal);
        txtSubTotal.setBounds(330, 390, 160, 40);
        getContentPane().add(txtISV);
        txtISV.setBounds(330, 440, 160, 30);
        getContentPane().add(txtDescuento);
        txtDescuento.setBounds(330, 480, 160, 40);

        txtTotalPagar.setEditable(false);
        txtTotalPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalPagarActionPerformed(evt);
            }
        });
        getContentPane().add(txtTotalPagar);
        txtTotalPagar.setBounds(330, 530, 160, 30);

        cboLista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lavado\t", "Alineado", "Balanceo", "Lavado de Motor", "Pintar el carro", "Enderesamiento", "Cambio de aceite", "Revisado de los borners", "Mantenimiento del carro", "Sistemas de freno", "Servicio Electronico", "Baterias", "Sistema de inyeccion" }));
        cboLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboListaMouseClicked(evt);
            }
        });
        cboLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboListaActionPerformed(evt);
            }
        });
        getContentPane().add(cboLista);
        cboLista.setBounds(330, 340, 190, 40);

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(240, 650, 140, 50);

        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Efectivo recibido");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(70, 570, 140, 21);

        txtNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre1);
        txtNombre1.setBounds(330, 90, 160, 30);

        cbxRtn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO tiene RTN", "SI tiene RTN" }));
        cbxRtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbxRtnMouseClicked(evt);
            }
        });
        cbxRtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxRtnActionPerformed(evt);
            }
        });
        getContentPane().add(cbxRtn);
        cbxRtn.setBounds(190, 130, 110, 30);

        txtCant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantActionPerformed(evt);
            }
        });
        getContentPane().add(txtCant);
        txtCant.setBounds(330, 250, 160, 30);

        jLabel13.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Repuestos  ");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(110, 350, 90, 21);

        lblFondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\proyecto final oficial\\src\\main\\java\\hn\\uth\\poo\\p3\\recursos\\imagenes1\\geometrical-background-design_1078-66 copia.jpg")); // NOI18N
        getContentPane().add(lblFondo);
        lblFondo.setBounds(0, -70, 626, 870);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCambioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtCambioActionPerformed

    private void txtRtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRtnActionPerformed

    private void txtEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEfectivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEfectivoActionPerformed

    private void txtPrecioRepuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioRepuestosActionPerformed
        // TODO add your handling code here:
        //frmBuscarPiezas.txtPrecio.getText();
    }//GEN-LAST:event_txtPrecioRepuestosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:        
        try {
            double cant=Double.parseDouble(txtCant.getText());         
            double precio=Double.parseDouble(txtPrecioRepuestos.getText());
            double ISV=Double.parseDouble(txtISV.getText());
            double efectivoRecibido=Double.parseDouble(txtEfectivo.getText());
            double Des=Double.parseDouble(txtDescuento.getText());
            double subtotal=Double.parseDouble(txtSubTotal.getText());
            
            double totalAPagar=cant*precio;
            double totalCambio=totalAPagar-efectivoRecibido;          
            double cantIsv=totalAPagar*ISV/100;
            double descuento=totalAPagar*Des/100;
            double totalGeneral=totalAPagar+cantIsv-descuento;
                
            if (totalCambio < efectivoRecibido) {
                JOptionPane.showMessageDialog(null, "Monto de dinero recibido incorrectamente", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            
            
            txtCambio.setText(""+totalCambio);
            txtTotalPagar.setText(""+totalGeneral);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cboListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboListaMouseClicked
        //         TODO add your handling code here:
    }//GEN-LAST:event_cboListaMouseClicked

    private void cboListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboListaActionPerformed
        // TODO add your handling code here:
        Servicios servicio=new Servicios();
        int itemTexto=cboLista.getSelectedIndex();
        switch (itemTexto) {
            case 0:
            servicio.setPrecio(342);
            break;
            case 1:
            servicio.setPrecio(360);
            break;
            case 2:
            servicio.setPrecio(744);
            break;
            case 3:
            servicio.setPrecio(415);
            break;
            case 4:
            servicio.setPrecio(561);
            break;
            case 5:
            servicio.setPrecio(934);
            break;
            case 6:
            servicio.setPrecio(321);
            break;
            case 7:
            servicio.setPrecio(503);
            break;
            case 8:
            servicio.setPrecio(211);
            break;
            case 9:
            servicio.setPrecio(123);
            break;
            case 10:
            servicio.setPrecio(3432);
            break;
            case 11:
            servicio.setPrecio(321);
            break;
            case 12:
            servicio.setPrecio(2312);
            break;
            
            default:
            break;
        }
        txtPrecioRepuestos.setText(String.valueOf(servicio.getPrecio()));
    }//GEN-LAST:event_cboListaActionPerformed

    private void txtNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre1ActionPerformed

    private void cbxRtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxRtnActionPerformed
        // TODO add your handling code here:
        int seleccion=cbxRtn.getSelectedIndex();
        if(seleccion==0){
            txtRtn.setEnabled(false);
        }
        if(seleccion==1){
            txtRtn.setEnabled(true);
        }
    }//GEN-LAST:event_cbxRtnActionPerformed

    private void cbxRtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxRtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxRtnMouseClicked

    private void txtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubTotalActionPerformed

    private void txtTotalPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalPagarActionPerformed

    private void txtCantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFactura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboLista;
    private javax.swing.JComboBox<String> cbxRtn;
    private java.awt.Label frmFactura;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JTextField txtCambio;
    private javax.swing.JTextField txtCant;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtEfectivo;
    private javax.swing.JTextField txtISV;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtPrecioRepuestos;
    private javax.swing.JTextField txtRtn;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTotalPagar;
    // End of variables declaration//GEN-END:variables
}
