/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hn.uth.poo.p3;

/**
 *
 * @author Dell
 */
public class frmMecanico extends javax.swing.JFrame {

    /**
     * Creates new form frmMecanic
     */
    public frmMecanico() {
        initComponents();
        setSize(700, 498);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblDiagnostico = new javax.swing.JLabel();
        lblListaRepuesto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaDiagnostico = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaListRespuesto = new javax.swing.JTextArea();
        lblFechaFinal = new javax.swing.JLabel();
        dcFechaInicio = new com.toedter.calendar.JDateChooser();
        btnMostrarTexto = new javax.swing.JButton();
        btnEnviar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        getContentPane().setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 51, 51));
        lblTitulo.setText("Mecánico");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(250, 30, 110, 32);

        lblDiagnostico.setFont(new java.awt.Font("Levenim MT", 1, 14)); // NOI18N
        lblDiagnostico.setForeground(new java.awt.Color(0, 51, 51));
        lblDiagnostico.setText("Diagnostico ");
        getContentPane().add(lblDiagnostico);
        lblDiagnostico.setBounds(80, 110, 87, 19);

        lblListaRepuesto.setFont(new java.awt.Font("Levenim MT", 1, 14)); // NOI18N
        lblListaRepuesto.setForeground(new java.awt.Color(0, 51, 51));
        lblListaRepuesto.setText("Lista de repuestos");
        getContentPane().add(lblListaRepuesto);
        lblListaRepuesto.setBounds(410, 110, 131, 19);

        txtaDiagnostico.setColumns(20);
        txtaDiagnostico.setRows(5);
        jScrollPane1.setViewportView(txtaDiagnostico);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 150, 166, 96);

        txtaListRespuesto.setColumns(20);
        txtaListRespuesto.setRows(5);
        jScrollPane2.setViewportView(txtaListRespuesto);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(390, 150, 166, 96);

        lblFechaFinal.setFont(new java.awt.Font("Levenim MT", 1, 14)); // NOI18N
        lblFechaFinal.setForeground(new java.awt.Color(0, 51, 51));
        lblFechaFinal.setText("Fecha Final:");
        getContentPane().add(lblFechaFinal);
        lblFechaFinal.setBounds(270, 250, 85, 19);
        getContentPane().add(dcFechaInicio);
        dcFechaInicio.setBounds(240, 290, 130, 30);

        btnMostrarTexto.setText("Mostrar Diagnostico");
        btnMostrarTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTextoActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrarTexto);
        btnMostrarTexto.setBounds(40, 300, 140, 50);

        btnEnviar.setText("Enviar Lista");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviar);
        btnEnviar.setBounds(450, 300, 120, 40);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(470, 280, 210, 180);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 670, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTextoActionPerformed
        // TODO add your handling code here:
        frmCarro.txtaDatos.setText(txtaDiagnostico.getText());
    }//GEN-LAST:event_btnMostrarTextoActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
        txtaListRespuesto.getText();
    }//GEN-LAST:event_btnEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMecanico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnMostrarTexto;
    private com.toedter.calendar.JDateChooser dcFechaInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDiagnostico;
    private javax.swing.JLabel lblFechaFinal;
    private javax.swing.JLabel lblListaRepuesto;
    private javax.swing.JLabel lblTitulo;
    public static javax.swing.JTextArea txtaDiagnostico;
    private javax.swing.JTextArea txtaListRespuesto;
    // End of variables declaration//GEN-END:variables
}
